version: '3'

services:
  nodejs:
    build:
      context: server
    image: nodejs
    container_name: nodejs
    restart: always
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "8080:8080"
      - "4000:4000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js 

  # db:
  #   image: mongo:4.0-xenial
  #   container_name: db
  #   restart: always
  #   env_file: .env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  #   volumes:     
  #     - dbdata:/data/db
  #   networks:
  #     - app-network  
  
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USERNAME
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  