FROM node:10

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

USER node

RUN npm install
RUN npm ci --only=production

# Bundle app source
COPY --chown=node:node . .

EXPOSE 8080 4000
CMD [ "node", "server.js" ]
